https://www.hitta.se/s√∂k?vad=lampor&riks=1&typ=ftg&sida=1
Exception in thread Scrape thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tacobaco/myprojects/SCRAPE_APP/code/scrape.py", line 109, in scrapeThread
    companies_dict = self.scrapeMainPage(self.url, pages)
  File "/Users/tacobaco/myprojects/SCRAPE_APP/code/scrape.py", line 127, in scrapeMainPage
    companys = soup.find_all('a', {'class': 'style_searchResultLink__2i2BY'})
AttributeError: 'str' object has no attribute 'find_all'

